# Generated by Django 3.0 on 2019-12-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField()),
                ('stationname', models.TextField()),
                ('address', models.TextField()),
                ('mapy', models.FloatField()),
                ('mapx', models.FloatField()),
                ('parkingnum', models.IntegerField()),
                ('possiblebikenum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rating', models.FloatField()),
                ('explain', models.TextField()),
                ('mapy', models.FloatField()),
                ('mapx', models.FloatField()),
                ('imagelink', models.TextField()),
                ('address', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
